// actionTypes.js

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';


export const CHAT_USER_MESSAGE_REQUEST = 'CHAT_USER_MESSAGE_REQUEST';
export const CHAT_USER_MESSAGE_SUCCESS = 'CHAT_USER_MESSAGE_SUCCESS';
export const CHAT_USER_MESSAGE_FAILURE = 'CHAT_USER_MESSAGE_FAILURE';


export const CHAT_AGENT_POLL_REQUEST = 'CHAT_AGENT_POLL_REQUEST';
export const CHAT_AGENT_POLL_SUCCESS = 'CHAT_AGENT_POLL_SUCCESS';
export const CHAT_AGENT_POLL_FAILURE = 'CHAT_AGENT_POLL_FAILURE';
