"""add_notification_table

Revision ID: a836a1102523
Revises: 2de435a564bd
Create Date: 2025-01-02 20:35:04.722142+00:00

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op

from informed.db_models import Notification, NotificationStatus
from informed.db_models.shared_types import EnumAsString

# revision identifiers, used by Alembic.
revision: str = "a836a1102523"
down_revision: str | None = "2de435a564bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("notification_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.Column("status", EnumAsString(NotificationStatus), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("chat_thread_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_thread_id"], ["chat_thread.chat_thread_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("notification_id"),
    )
    op.create_index(
        op.f("ix_notification_chat_thread_id"),
        "notification",
        ["chat_thread_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_chat_thread_id"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
