"""01_add_queries_table

Revision ID: 82d260adb00a
Revises: d1c944af4368
Create Date: 2024-09-30 19:07:39.514918+00:00

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from informed.db_models.shared_types import JSONBFromPydantic, EnumAsString
from informed.db_models.query import QuerySource, QueryState
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82d260adb00a"
down_revision: str | None = "d1c944af4368"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "queries",
        sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("query_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", EnumAsString(QueryState), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("query_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("queries")
    # ### end Alembic commands ###
