"""add_weather_notifications_table

Revision ID: 2c0320a83ec8
Revises: 4a18bfc8bfac
Create Date: 2024-11-21 19:40:48.493732+00:00

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2c0320a83ec8"
down_revision: str | None = "4a18bfc8bfac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("zip_code", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weather_notifications_zip_code"),
        "weather_notifications",
        ["zip_code"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weather_notifications_zip_code"), table_name="weather_notifications"
    )
    op.drop_table("weather_notifications")
    # ### end Alembic commands ###
