"""make_sources_and_findings_nullable

Revision ID: 7db8dcf4cd6b
Revises: 82d260adb00a
Create Date: 2024-11-21 18:25:30.536251+00:00

"""

from typing import Sequence

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7db8dcf4cd6b"
down_revision: str | None = "82d260adb00a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "queries",
        "sources",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "queries",
        "findings",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "user_details",
        "language",
        existing_type=postgresql.ENUM("ENGLISH", "SPANISH", name="language"),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_details",
        "language",
        existing_type=postgresql.ENUM("ENGLISH", "SPANISH", name="language"),
        nullable=False,
    )
    op.alter_column(
        "queries",
        "findings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "queries",
        "sources",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###
